// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: proto/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceChecker_CheckResources_FullMethodName = "/agent.ResourceChecker/CheckResources"
)

// ResourceCheckerClient is the client API for ResourceChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceCheckerClient interface {
	CheckResources(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
}

type resourceCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceCheckerClient(cc grpc.ClientConnInterface) ResourceCheckerClient {
	return &resourceCheckerClient{cc}
}

func (c *resourceCheckerClient) CheckResources(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, ResourceChecker_CheckResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceCheckerServer is the server API for ResourceChecker service.
// All implementations must embed UnimplementedResourceCheckerServer
// for forward compatibility.
type ResourceCheckerServer interface {
	CheckResources(context.Context, *ResourceRequest) (*ResourceResponse, error)
	mustEmbedUnimplementedResourceCheckerServer()
}

// UnimplementedResourceCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceCheckerServer struct{}

func (UnimplementedResourceCheckerServer) CheckResources(context.Context, *ResourceRequest) (*ResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckResources not implemented")
}
func (UnimplementedResourceCheckerServer) mustEmbedUnimplementedResourceCheckerServer() {}
func (UnimplementedResourceCheckerServer) testEmbeddedByValue()                         {}

// UnsafeResourceCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceCheckerServer will
// result in compilation errors.
type UnsafeResourceCheckerServer interface {
	mustEmbedUnimplementedResourceCheckerServer()
}

func RegisterResourceCheckerServer(s grpc.ServiceRegistrar, srv ResourceCheckerServer) {
	// If the following call pancis, it indicates UnimplementedResourceCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceChecker_ServiceDesc, srv)
}

func _ResourceChecker_CheckResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceCheckerServer).CheckResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceChecker_CheckResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceCheckerServer).CheckResources(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceChecker_ServiceDesc is the grpc.ServiceDesc for ResourceChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.ResourceChecker",
	HandlerType: (*ResourceCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckResources",
			Handler:    _ResourceChecker_CheckResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent.proto",
}
